load("@prelude//toolchains:cxx.bzl", "system_cxx_toolchain")
load("@prelude//toolchains:genrule.bzl", "system_genrule_toolchain")
load("@prelude//toolchains:python.bzl", "system_python_bootstrap_toolchain", "system_python_toolchain")
load("defs.bzl", "cabal_toolchain", "haskell_toolchain", "something")
load("ghcup/defs.bzl", "download_cabal_distribution", "download_ghc_distribution")

something(name = "something")

system_cxx_toolchain(
    name = "cxx",
    visibility = ["PUBLIC"],
)

system_genrule_toolchain(
    name = "genrule",
    visibility = ["PUBLIC"],
)

system_python_toolchain(
    name = "python",
    visibility = ["PUBLIC"],
)

system_python_bootstrap_toolchain(
    name = "python_bootstrap",
    visibility = ["PUBLIC"],
)

download_ghc_distribution(
    name = "ghc-9.12.2",
    version = "9.12.2",
)

haskell_toolchain(
    name = "haskell",
    distribution = ":ghc-9.12.2",
    visibility = ["PUBLIC"],
)

download_cabal_distribution(
    name = "cabal-3.14.2.0",
    version = "3.14.2.0",
)

cabal_toolchain(
    name = "cabal",
    distribution = ":cabal-3.14.2.0",
    visibility = ["PUBLIC"],
)
