# buildifier: disable=module-docstring
load("//rules/haskell/cabal_install/interpret_plan.bzl", "interpret_plan")
load("//rules/haskell/cabal_install/plan.bzl", "plan")

plan(
    name = "plan",
    project_file = "cabal.project",
    targets = ["shake"],
)

# The output of :plan
interpret_plan("shake", """
{
  "cabal-version": "3.14.2.0",
  "cabal-lib-version": "3.14.2.0",
  "compiler-id": "ghc-9.12.2",
  "os": "linux",
  "arch": "x86_64",
  "install-plan": [
    {
      "type": "pre-existing",
      "id": "array-0.5.8.0-8724",
      "pkg-name": "array",
      "pkg-version": "0.5.8.0",
      "depends": [
        "base-4.21.0.0-b7a5"
      ]
    },
    {
      "type": "pre-existing",
      "id": "base-4.21.0.0-b7a5",
      "pkg-name": "base",
      "pkg-version": "4.21.0.0",
      "depends": [
        "ghc-internal-9.1202.0-7700",
        "ghc-prim-0.13.0-00de"
      ]
    },
    {
      "type": "pre-existing",
      "id": "binary-0.8.9.3-886c",
      "pkg-name": "binary",
      "pkg-version": "0.8.9.3",
      "depends": [
        "array-0.5.8.0-8724",
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "containers-0.7-e3bc"
      ]
    },
    {
      "type": "pre-existing",
      "id": "bytestring-0.12.2.0-d099",
      "pkg-name": "bytestring",
      "pkg-version": "0.12.2.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "ghc-prim-0.13.0-00de",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "configured",
      "id": "clock-0.8.4-ab56355be15573144b9d149de6386378be66acfe85841d3559d7ec3fb4a03b38",
      "pkg-name": "clock",
      "pkg-version": "0.8.4",
      "flags": {
        "llvm": false
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "b938655b00cf204ce69abfff946021bed111d2609a9f7a9c22e28a1a202e9115",
      "pkg-src-sha256": "6ae9898afe788a5e334cd5fad5d18a3c2e8e59fa09aaf7b957dbb38a4767df2e",
      "depends": [
        "base-4.21.0.0-b7a5"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "containers-0.7-e3bc",
      "pkg-name": "containers",
      "pkg-version": "0.7",
      "depends": [
        "array-0.5.8.0-8724",
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "pre-existing",
      "id": "deepseq-1.5.1.0-58c3",
      "pkg-name": "deepseq",
      "pkg-version": "1.5.1.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "ghc-prim-0.13.0-00de"
      ]
    },
    {
      "type": "pre-existing",
      "id": "directory-1.3.9.0-ca9f",
      "pkg-name": "directory",
      "pkg-version": "1.3.9.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "file-io-0.1.5-5775",
        "filepath-1.5.4.0-c656",
        "os-string-2.0.7-3307",
        "time-1.14-3339",
        "unix-2.8.6.0-2805"
      ]
    },
    {
      "type": "pre-existing",
      "id": "exceptions-0.10.9-fdde",
      "pkg-name": "exceptions",
      "pkg-version": "0.10.9",
      "depends": [
        "base-4.21.0.0-b7a5",
        "mtl-2.3.1-6d75",
        "stm-2.5.3.1-6dd9",
        "template-haskell-2.23.0.0-1f7b",
        "transformers-0.6.1.2-c7d6"
      ]
    },
    {
      "type": "configured",
      "id": "extra-1.8.1-03e9a6406e5de33908aefe6b294da9d97f889c50f9907d5864cfcbb3de194c17",
      "pkg-name": "extra",
      "pkg-version": "1.8.1",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "b9c360f2f3fbff5ca04656b7aa0a91b254ac7de7e4b959bae4688a178ffd79d1",
      "pkg-src-sha256": "66a7d6d718646a7bda822d67550dc185c6e25ad1f7fecf06fc132e300098b598",
      "depends": [
        "base-4.21.0.0-b7a5",
        "clock-0.8.4-ab56355be15573144b9d149de6386378be66acfe85841d3559d7ec3fb4a03b38",
        "directory-1.3.9.0-ca9f",
        "filepath-1.5.4.0-c656",
        "process-1.6.25.0-0514",
        "time-1.14-3339",
        "unix-2.8.6.0-2805"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "file-io-0.1.5-5775",
      "pkg-name": "file-io",
      "pkg-version": "0.1.5",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "filepath-1.5.4.0-c656",
        "os-string-2.0.7-3307",
        "unix-2.8.6.0-2805"
      ]
    },
    {
      "type": "pre-existing",
      "id": "filepath-1.5.4.0-c656",
      "pkg-name": "filepath",
      "pkg-version": "1.5.4.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "exceptions-0.10.9-fdde",
        "os-string-2.0.7-3307",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "configured",
      "id": "filepattern-0.1.3-3cb92b4886b28e60147212a92bf43c2686595d01a013ef0e3d0d62fa6f036c20",
      "pkg-name": "filepattern",
      "pkg-version": "0.1.3",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "372c1733d83b90045eb29da9f010fed79bfef8771ce65eb126a1d83ecc54a9a2",
      "pkg-src-sha256": "cc445d439ea2f65cac7604d3578aa2c3a62e5a91dc989f4ce5b3390db9e59636",
      "depends": [
        "base-4.21.0.0-b7a5",
        "directory-1.3.9.0-ca9f",
        "extra-1.8.1-03e9a6406e5de33908aefe6b294da9d97f889c50f9907d5864cfcbb3de194c17",
        "filepath-1.5.4.0-c656"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "ghc-bignum-1.3-4dbb",
      "pkg-name": "ghc-bignum",
      "pkg-version": "1.3",
      "depends": [
        "ghc-prim-0.13.0-00de"
      ]
    },
    {
      "type": "pre-existing",
      "id": "ghc-boot-th-9.12.2-612d",
      "pkg-name": "ghc-boot-th",
      "pkg-version": "9.12.2",
      "depends": [
        "base-4.21.0.0-b7a5",
        "ghc-internal-9.1202.0-7700",
        "ghc-prim-0.13.0-00de",
        "pretty-1.1.3.6-66c0"
      ]
    },
    {
      "type": "pre-existing",
      "id": "ghc-internal-9.1202.0-7700",
      "pkg-name": "ghc-internal",
      "pkg-version": "9.1202.0",
      "depends": [
        "ghc-bignum-1.3-4dbb",
        "ghc-prim-0.13.0-00de",
        "rts-1.0.2"
      ]
    },
    {
      "type": "pre-existing",
      "id": "ghc-prim-0.13.0-00de",
      "pkg-name": "ghc-prim",
      "pkg-version": "0.13.0",
      "depends": [
        "rts-1.0.2"
      ]
    },
    {
      "type": "configured",
      "id": "hashable-1.5.1.0-13cb1a4182d8afe64f275be6dfdaf441ff1c43a90236765d44d5e8d52f0e6a90",
      "pkg-name": "hashable",
      "pkg-version": "1.5.1.0",
      "flags": {
        "arch-native": false,
        "random-initial-seed": false
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "140fc5adad166f7b527567cbd26ff481e8da4a66bdfc84be3ddf28dbeb66f275",
      "pkg-src-sha256": "ed0b7c10ce92c9ffe45420dadc38c6d39db486ff3633ff13567cc9f75f79b112",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "containers-0.7-e3bc",
        "deepseq-1.5.1.0-58c3",
        "filepath-1.5.4.0-c656",
        "os-string-2.0.7-3307",
        "text-2.1.2-c196"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "heaps-0.4.1-b6185c6508d3f7e28ce77a73ec392f9d7b99c845e68e96f835a6c03dac435bc8",
      "pkg-name": "heaps",
      "pkg-version": "0.4.1",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "74ce60a23b8ef247b8bca71eeb38289e82b3b5e83b2383600b2c838a68218068",
      "pkg-src-sha256": "8763a4663a2d0b3c912400a547d66ae11b46a954403b6747272148e950aa0382",
      "depends": [
        "base-4.21.0.0-b7a5"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "js-dgtable-0.5.2-22c97fd724a34486295d9b865f431fd0b6adb5b326f3d040c2a8a5ee06986889",
      "pkg-name": "js-dgtable",
      "pkg-version": "0.5.2",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "f75cb4fa53c88c65794becdd48eb0d3b2b8abd89a3d5c19e87af91f5225c15e4",
      "pkg-src-sha256": "e28dd65bee8083b17210134e22e01c6349dc33c3b7bd17705973cd014e9f20ac",
      "depends": [
        "base-4.21.0.0-b7a5"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "js-flot-0.8.3-19446ca05c366d726d441d38fef0914175dae36da31d5e7a1760061cd4b4ddad",
      "pkg-name": "js-flot",
      "pkg-version": "0.8.3",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "4c1c447a9a2fba0adba6d30678302a30c32b9dfde9e7aa9e9156483e1545096d",
      "pkg-src-sha256": "1ba2f2a6b8d85da76c41f526c98903cbb107f8642e506c072c1e7e3c20fe5e7a",
      "depends": [
        "base-4.21.0.0-b7a5"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "js-jquery-3.7.1-e718165cdb7d6bbbfe1b30d06f540e4dc27832a17e7db7c107b1adcdb728db32",
      "pkg-name": "js-jquery",
      "pkg-version": "3.7.1",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "fdbdfd4d413848c678a3737f2b985a5db66b796c6847b1ae08246ea3795c0ba2",
      "pkg-src-sha256": "a087fa01a1c52f5386d43f5355f64841c5a4b56b53720090d66b5aa00bfeb106",
      "depends": [
        "base-4.21.0.0-b7a5"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "mtl-2.3.1-6d75",
      "pkg-name": "mtl",
      "pkg-version": "2.3.1",
      "depends": [
        "base-4.21.0.0-b7a5",
        "transformers-0.6.1.2-c7d6"
      ]
    },
    {
      "type": "pre-existing",
      "id": "os-string-2.0.7-3307",
      "pkg-name": "os-string",
      "pkg-version": "2.0.7",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "exceptions-0.10.9-fdde",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "pre-existing",
      "id": "pretty-1.1.3.6-66c0",
      "pkg-name": "pretty",
      "pkg-version": "1.1.3.6",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "ghc-prim-0.13.0-00de"
      ]
    },
    {
      "type": "configured",
      "id": "primitive-0.9.1.0-522834ae5c8ea9918e05e6a16f288f75f02fd4d0c53f225dbab8df01e4a15af6",
      "pkg-name": "primitive",
      "pkg-version": "0.9.1.0",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "756b222c715bc6ef5ba81fa69cdbaa20c5c53beb6f16f174b8bacc93a6d239f0",
      "pkg-src-sha256": "44b4de41813c7bc5db8a57f87c3612a069b65086946268ba165097252ebd3d76",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "template-haskell-2.23.0.0-1f7b",
        "transformers-0.6.1.2-c7d6"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "process-1.6.25.0-0514",
      "pkg-name": "process",
      "pkg-version": "1.6.25.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "directory-1.3.9.0-ca9f",
        "filepath-1.5.4.0-c656",
        "unix-2.8.6.0-2805"
      ]
    },
    {
      "type": "configured",
      "id": "random-1.3.1-92cb74323cd599892f32a7a06c0e4ded1463d5a8ccab08231b9576f779734956",
      "pkg-name": "random",
      "pkg-version": "1.3.1",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "0b4f649c3e78713b2ccad1535251ee34b148237fb2229d7058c2b1d9ccc324b8",
      "pkg-src-sha256": "d840ac83f265b0cfa2a678f8ec78627eb50cf9be2f067c52c8a4239c29b71a35",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "mtl-2.3.1-6d75",
        "splitmix-0.1.3.2-d508f615fac36dd4faf3cff8a065f8bcec380927d07332ee4a70b0d4470d4a8a",
        "transformers-0.6.1.2-c7d6"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "rts-1.0.2",
      "pkg-name": "rts",
      "pkg-version": "1.0.2",
      "depends": []
    },
    {
      "type": "configured",
      "id": "shake-0.19.9-60c84e0d8cc940754887ce9b264a3deef6810d616bafae92ab23c765c6a73459",
      "pkg-name": "shake",
      "pkg-version": "0.19.9",
      "flags": {
        "cloud": false,
        "embed-files": false,
        "portable": false,
        "threaded": true
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "8704f35f7857f71adef2b74aafb5580f73dfab004a804718d418c16798f4a186",
      "pkg-src-sha256": "4176d6e38c3b7813f019f2377466d9f01db842056eec1cdaa8a23b80ceddcb8a",
      "depends": [
        "base-4.21.0.0-b7a5",
        "binary-0.8.9.3-886c",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "directory-1.3.9.0-ca9f",
        "extra-1.8.1-03e9a6406e5de33908aefe6b294da9d97f889c50f9907d5864cfcbb3de194c17",
        "filepath-1.5.4.0-c656",
        "filepattern-0.1.3-3cb92b4886b28e60147212a92bf43c2686595d01a013ef0e3d0d62fa6f036c20",
        "hashable-1.5.1.0-13cb1a4182d8afe64f275be6dfdaf441ff1c43a90236765d44d5e8d52f0e6a90",
        "heaps-0.4.1-b6185c6508d3f7e28ce77a73ec392f9d7b99c845e68e96f835a6c03dac435bc8",
        "js-dgtable-0.5.2-22c97fd724a34486295d9b865f431fd0b6adb5b326f3d040c2a8a5ee06986889",
        "js-flot-0.8.3-19446ca05c366d726d441d38fef0914175dae36da31d5e7a1760061cd4b4ddad",
        "js-jquery-3.7.1-e718165cdb7d6bbbfe1b30d06f540e4dc27832a17e7db7c107b1adcdb728db32",
        "primitive-0.9.1.0-522834ae5c8ea9918e05e6a16f288f75f02fd4d0c53f225dbab8df01e4a15af6",
        "process-1.6.25.0-0514",
        "random-1.3.1-92cb74323cd599892f32a7a06c0e4ded1463d5a8ccab08231b9576f779734956",
        "time-1.14-3339",
        "transformers-0.6.1.2-c7d6",
        "unix-2.8.6.0-2805",
        "unordered-containers-0.2.21-fcd57e729ab9cd3f49ad5e61e00e67e1d8e95c5b62b2c2f70acd42f8c00c392e",
        "utf8-string-1.0.2-9ca44a8a130762ad9c3a53868163bbf84da0c4d0d3fd75539327555666ba6d0f"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "shake-0.19.9-e-shake-59138ccb836da9a4a51957b5e31580d274045c1319700c4d2c133423e8f272b4",
      "pkg-name": "shake",
      "pkg-version": "0.19.9",
      "flags": {
        "cloud": false,
        "embed-files": false,
        "portable": false,
        "threaded": true
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "8704f35f7857f71adef2b74aafb5580f73dfab004a804718d418c16798f4a186",
      "pkg-src-sha256": "4176d6e38c3b7813f019f2377466d9f01db842056eec1cdaa8a23b80ceddcb8a",
      "depends": [
        "base-4.21.0.0-b7a5",
        "binary-0.8.9.3-886c",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "directory-1.3.9.0-ca9f",
        "extra-1.8.1-03e9a6406e5de33908aefe6b294da9d97f889c50f9907d5864cfcbb3de194c17",
        "filepath-1.5.4.0-c656",
        "filepattern-0.1.3-3cb92b4886b28e60147212a92bf43c2686595d01a013ef0e3d0d62fa6f036c20",
        "hashable-1.5.1.0-13cb1a4182d8afe64f275be6dfdaf441ff1c43a90236765d44d5e8d52f0e6a90",
        "heaps-0.4.1-b6185c6508d3f7e28ce77a73ec392f9d7b99c845e68e96f835a6c03dac435bc8",
        "js-dgtable-0.5.2-22c97fd724a34486295d9b865f431fd0b6adb5b326f3d040c2a8a5ee06986889",
        "js-flot-0.8.3-19446ca05c366d726d441d38fef0914175dae36da31d5e7a1760061cd4b4ddad",
        "js-jquery-3.7.1-e718165cdb7d6bbbfe1b30d06f540e4dc27832a17e7db7c107b1adcdb728db32",
        "primitive-0.9.1.0-522834ae5c8ea9918e05e6a16f288f75f02fd4d0c53f225dbab8df01e4a15af6",
        "process-1.6.25.0-0514",
        "random-1.3.1-92cb74323cd599892f32a7a06c0e4ded1463d5a8ccab08231b9576f779734956",
        "time-1.14-3339",
        "transformers-0.6.1.2-c7d6",
        "unix-2.8.6.0-2805",
        "unordered-containers-0.2.21-fcd57e729ab9cd3f49ad5e61e00e67e1d8e95c5b62b2c2f70acd42f8c00c392e",
        "utf8-string-1.0.2-9ca44a8a130762ad9c3a53868163bbf84da0c4d0d3fd75539327555666ba6d0f"
      ],
      "exe-depends": [],
      "component-name": "exe:shake",
      "bin-file": "/home/andrea/.local/state/cabal/store/ghc-9.12.2-5327/shake-0.19.9-e-shake-59138ccb836da9a4a51957b5e31580d274045c1319700c4d2c133423e8f272b4/bin/shake"
    },
    {
      "type": "configured",
      "id": "splitmix-0.1.3.2-d508f615fac36dd4faf3cff8a065f8bcec380927d07332ee4a70b0d4470d4a8a",
      "pkg-name": "splitmix",
      "pkg-version": "0.1.3.2",
      "flags": {
        "optimised-mixer": false
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "a557cff65eed1f70f3a3b468423cd58e7a9a9564c5cc00c76a13de64dec9bcbd",
      "pkg-src-sha256": "a61d4e8b30f5a16526d7d31171b674ae7924d2207f378060d13363bd8794de8c",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "pre-existing",
      "id": "stm-2.5.3.1-6dd9",
      "pkg-name": "stm",
      "pkg-version": "2.5.3.1",
      "depends": [
        "array-0.5.8.0-8724",
        "base-4.21.0.0-b7a5"
      ]
    },
    {
      "type": "pre-existing",
      "id": "template-haskell-2.23.0.0-1f7b",
      "pkg-name": "template-haskell",
      "pkg-version": "2.23.0.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "ghc-boot-th-9.12.2-612d"
      ]
    },
    {
      "type": "pre-existing",
      "id": "text-2.1.2-c196",
      "pkg-name": "text",
      "pkg-version": "2.1.2",
      "depends": [
        "array-0.5.8.0-8724",
        "base-4.21.0.0-b7a5",
        "binary-0.8.9.3-886c",
        "bytestring-0.12.2.0-d099",
        "deepseq-1.5.1.0-58c3",
        "ghc-prim-0.13.0-00de",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "pre-existing",
      "id": "time-1.14-3339",
      "pkg-name": "time",
      "pkg-version": "1.14",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "template-haskell-2.23.0.0-1f7b"
      ]
    },
    {
      "type": "pre-existing",
      "id": "transformers-0.6.1.2-c7d6",
      "pkg-name": "transformers",
      "pkg-version": "0.6.1.2",
      "depends": [
        "base-4.21.0.0-b7a5"
      ]
    },
    {
      "type": "pre-existing",
      "id": "unix-2.8.6.0-2805",
      "pkg-name": "unix",
      "pkg-version": "2.8.6.0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099",
        "filepath-1.5.4.0-c656",
        "os-string-2.0.7-3307",
        "time-1.14-3339"
      ]
    },
    {
      "type": "configured",
      "id": "unordered-containers-0.2.21-fcd57e729ab9cd3f49ad5e61e00e67e1d8e95c5b62b2c2f70acd42f8c00c392e",
      "pkg-name": "unordered-containers",
      "pkg-version": "0.2.21",
      "flags": {
        "debug": false
      },
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "c5de1fb3377ed3c5f4cd851a771d1acc5c37d2f6bef0a499295c0e8857da5605",
      "pkg-src-sha256": "3b2ad1522b546e61960153257d1e5d239eeec5e83da847d5cb4d896a5bb7f9c0",
      "depends": [
        "base-4.21.0.0-b7a5",
        "deepseq-1.5.1.0-58c3",
        "hashable-1.5.1.0-13cb1a4182d8afe64f275be6dfdaf441ff1c43a90236765d44d5e8d52f0e6a90",
        "template-haskell-2.23.0.0-1f7b"
      ],
      "exe-depends": [],
      "component-name": "lib"
    },
    {
      "type": "configured",
      "id": "utf8-string-1.0.2-9ca44a8a130762ad9c3a53868163bbf84da0c4d0d3fd75539327555666ba6d0f",
      "pkg-name": "utf8-string",
      "pkg-version": "1.0.2",
      "flags": {},
      "style": "global",
      "pkg-src": {
        "type": "repo-tar",
        "repo": {
          "type": "secure-repo",
          "uri": "http://hackage.haskell.org/"
        }
      },
      "pkg-cabal-sha256": "79416292186feeaf1f60e49ac5a1ffae9bf1b120e040a74bf0e81ca7f1d31d3f",
      "pkg-src-sha256": "ee48deada7600370728c4156cb002441de770d0121ae33a68139a9ed9c19b09a",
      "depends": [
        "base-4.21.0.0-b7a5",
        "bytestring-0.12.2.0-d099"
      ],
      "exe-depends": [],
      "component-name": "lib"
    }
  ]
}
""")
