load("//rules/haskell:defs.bzl", "haskell_binary")

haskell_binary(
    name = "parse_fields",
    srcs = {
        "Main.hs": "parse_fields.hs",
    },
    toolchain_libs = [
        "base",
        "bytestring",
        "Cabal",
        "Cabal-syntax",
    ],
)
