export_file(
    name = "run.sh",
    src = "tools/run.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "register.sh",
    src = "tools/register.sh",
    visibility = ["PUBLIC"],
)

export_file(
    name = "find_modules.sh",
    src = "tools/find_modules.sh",
    visibility = ["PUBLIC"],
)
