"""
The cabal_macros.h header, see Distribution.Simple.Build.Macros.
"""

load(":providers.bzl", "mangle")

Versioned = record(name = str, version = str)

CabalMacroContext = record(
    package_version = str,
    package_key = str | None,
    component_id = str | None,
    # The package itself and its direct dependencies
    packages = list[Versioned],
    # The programs whose version is known, e.g. ghc
    tools = list[Versioned],
)

def _major_minor(version: str) -> (int, int, int):
    nums = [int(n) for n in version.split(".") if n.isdigit()] + [0, 0, 0]
    return (nums[0], nums[1], nums[2])

def _version_macros(prefix: str, kind: str, v: Versioned) -> str:
    name = mangle(v.name)
    x, y, z = _major_minor(v.version)
    return """/* {kind} {pkg}-{version} */
#ifndef {prefix}VERSION_{name}
#define {prefix}VERSION_{name} "{version}"
#endif /* {prefix}VERSION_{name} */
#ifndef MIN_{prefix}VERSION_{name}
#define MIN_{prefix}VERSION_{name}(major1,major2,minor) (\\
  (major1) <  {x} || \\
  (major1) == {x} && (major2) <  {y} || \\
  (major1) == {x} && (major2) == {y} && (minor) <= {z})
#endif /* MIN_{prefix}VERSION_{name} */

""".format(prefix = prefix, kind = kind, pkg = v.name, name = name, version = v.version, x = x, y = y, z = z)

def _define(name: str, value: str) -> str:
    return """#ifndef {name}
#define {name} "{value}"
#endif /* {name} */

""".format(name = name, value = value)

def cabal_macros_gen(m: CabalMacroContext) -> str:
    s = "/* DO NOT EDIT: This file is automatically generated by the cabal_simple rules */\n\n"
    for p in m.packages:
        s += _version_macros("", "package", p)
    for t in m.tools:
        s += _version_macros("TOOL_", "tool", t)
    if m.package_key:
        s += _define("CURRENT_PACKAGE_KEY", m.package_key)
    if m.component_id:
        s += _define("CURRENT_COMPONENT_ID", m.component_id)
    s += _define("CURRENT_PACKAGE_VERSION", m.package_version)
    return s
