"""
The autogenerated modules Paths_<pkg> and PackageInfo_<pkg>, see
Distribution.Simple.Build.PathsModule and
Distribution.Simple.Build.PackageInfoModule.
"""

load(":providers.bzl", "mangle")

def manglePkgName(name: str) -> str:
    return mangle(name)

def _version_digits(version: str) -> str:
    return "[" + ",".join([n for n in version.split(".") if n.isdigit()]) + "]"

def hs_string(s: str) -> str:
    """Render a Haskell string literal.

    Args:
      s: any string
    Returns:
      the literal, quotes included
    """
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'

# This follows the "absolute" variant of Cabal's Paths_pkg.template.hs, except
# that the directories do not have to be absolute.
_paths_template = """{{-# LANGUAGE NoRebindableSyntax #-}}
{{-# OPTIONS_GHC -w #-}}
module Paths_{name} (
    version,
    getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir,
    getDataFileName, getSysconfDir
  ) where

import qualified Control.Exception as Exception
import Data.Version (Version(..))
import System.Environment (getEnv)
import Prelude

catchIO :: IO a -> (Exception.IOException -> IO a) -> IO a
catchIO = Exception.catch

version :: Version
version = Version {version_digits} []

getDataFileName :: FilePath -> IO FilePath
getDataFileName name = do
  dir <- getDataDir
  return (dir `joinFileName` name)

getBinDir, getLibDir, getDynLibDir, getDataDir, getLibexecDir, getSysconfDir :: IO FilePath

bindir, libdir, dynlibdir, datadir, libexecdir, sysconfdir :: FilePath
bindir     = "{bindir}"
libdir     = "{libdir}"
dynlibdir  = "{dynlibdir}"
datadir    = "{datadir}"
libexecdir = "{libexecdir}"
sysconfdir = "{sysconfdir}"

getBinDir     = catchIO (getEnv "{name}_bindir")     (\\_ -> return bindir)
getLibDir     = catchIO (getEnv "{name}_libdir")     (\\_ -> return libdir)
getDynLibDir  = catchIO (getEnv "{name}_dynlibdir")  (\\_ -> return dynlibdir)
getDataDir    = catchIO (getEnv "{name}_datadir")    (\\_ -> return datadir)
getLibexecDir = catchIO (getEnv "{name}_libexecdir") (\\_ -> return libexecdir)
getSysconfDir = catchIO (getEnv "{name}_sysconfdir") (\\_ -> return sysconfdir)

joinFileName :: String -> String -> FilePath
joinFileName ""  fname = fname
joinFileName "." fname = fname
joinFileName dir ""    = dir
joinFileName dir@(c:cs) fname
  | isPathSeparator (lastChar c cs) = dir ++ fname
  | otherwise                       = dir ++ pathSeparator : fname
 where
  lastChar x [] = x
  lastChar _ (x:xs) = lastChar x xs

pathSeparator :: Char
pathSeparator = '/'

isPathSeparator :: Char -> Bool
isPathSeparator c = c == '/'
"""

# A directory is either a literal or something that mentions artifacts.
PathsModuleCtx = record(
    package_name = str,
    package_version = str,
    bindir = str | cmd_args,
    libdir = str | cmd_args,
    dynlibdir = str | cmd_args,
    datadir = str | cmd_args,
    libexecdir = str | cmd_args,
    sysconfdir = str | cmd_args,
)

def mk_paths_module(module_ctx: PathsModuleCtx) -> cmd_args:
    """Generate the contents of Paths_<pkg>.hs

    Args:
      module_ctx: what goes in the module
    Returns:
      a single argument, suitable for `actions.write`
    """
    dirs = {
        "bindir": module_ctx.bindir,
        "datadir": module_ctx.datadir,
        "dynlibdir": module_ctx.dynlibdir,
        "libdir": module_ctx.libdir,
        "libexecdir": module_ctx.libexecdir,
        "sysconfdir": module_ctx.sysconfdir,
    }

    # Directories can be artifacts, which cannot be formatted into a string:
    # leave a marker and cut the text there.
    marker = "\0"
    text = _paths_template.format(
        name = manglePkgName(module_ctx.package_name),
        version_digits = _version_digits(module_ctx.package_version),
        **{k: marker + k + marker for k in dirs}
    )
    return cmd_args(
        [dirs[part] if i % 2 == 1 else part for i, part in enumerate(text.split(marker))],
        delimiter = "",
    )

def mk_package_info_module(
        package_name: str,
        package_version: str,
        synopsis: str = "",
        copyright: str = "",
        homepage: str = "") -> str:
    return """{{-# LANGUAGE NoRebindableSyntax #-}}
{{-# OPTIONS_GHC -w #-}}
module PackageInfo_{mangled} (
    name,
    version,
    synopsis,
    copyright,
    homepage,
  ) where

import Data.Version (Version(..))
import Prelude

name :: String
name = {name}
version :: Version
version = Version {version_digits} []

synopsis :: String
synopsis = {synopsis}
copyright :: String
copyright = {copyright}
homepage :: String
homepage = {homepage}
""".format(
        mangled = manglePkgName(package_name),
        name = hs_string(package_name),
        version_digits = _version_digits(package_version),
        synopsis = hs_string(synopsis),
        copyright = hs_string(copyright),
        homepage = hs_string(homepage),
    )

def _cabal_paths_module_impl(ctx: AnalysisContext) -> list[Provider]:
    s = mk_paths_module(PathsModuleCtx(
        package_name = ctx.attrs.package_name,
        package_version = ctx.attrs.package_version,
        bindir = ctx.attrs.bindir,
        libdir = ctx.attrs.libdir,
        dynlibdir = ctx.attrs.dynlibdir,
        datadir = ctx.attrs.datadir,
        libexecdir = ctx.attrs.libexecdir,
        sysconfdir = ctx.attrs.sysconfdir,
    ))
    out = ctx.actions.write("Paths_{}.hs".format(manglePkgName(ctx.attrs.package_name)), s)
    return [DefaultInfo(default_output = out)]

cabal_paths_module = rule(
    impl = _cabal_paths_module_impl,
    attrs = {
        "bindir": attrs.string(),
        "datadir": attrs.string(),
        "dynlibdir": attrs.string(),
        "libdir": attrs.string(),
        "libexecdir": attrs.string(),
        "package_name": attrs.string(),
        "package_version": attrs.string(),
        "sysconfdir": attrs.string(),
    },
)
