load("@prelude//rules.bzl", "haskell_library")
load("//rules/haskell:defs.bzl", "haskell_binary")

# A library and an executable built by the Haskell rules of the prelude, on
# top of a library built by the cabal_simple rules.
#
# Both have to use the same compiler. The prelude rules use toolchains//:haskell,
# so the cabal_simple library has to be built with the same binary distribution:
#
#   buck2 run --config cabal.ghc_toolchain=toolchains//:ghc-9.12.2-bindist //examples/prelude:exe

haskell_library(
    name = "lib",
    srcs = ["Report.hs"],
    deps = ["//examples/hello:lib"],
)

haskell_binary(
    name = "exe",
    srcs = ["Main.hs"],
    link_style = "static",
    toolchain_libs = ["base"],
    deps = [":lib"],
)
