load("@root//rules/haskell:toolchain.bzl", "haskell_toolchain")

toolchain_alias(
    name = "ghc-9.10.1",
    actual = "//haskell/ghc-9.10.1:haskell_toolchain",
    visibility = ["PUBLIC"],
)

toolchain_alias(
    name = "ghc-9.8.2",
    actual = "//haskell/ghc-9.8.2:haskell_toolchain",
    visibility = ["PUBLIC"],
)
