# buildifier: disable=module-docstring
load("@root//rules/haskell:toolchain.bzl", "haskell_toolchain")

haskell_toolchain(
    name = "haskell",
    compiler = "ghc-9.8.2",
    linker = "ghc-9.8.2",
    packager = "ghc-pkg-9.8.2",
    haddock = "haddock-9.8.2",
    packages = [
        ":Cabal",
        ":Cabal-syntax",
        ":array",
        ":base",
        ":binary",
        ":bytestring",
        ":containers",
        ":deepseq",
        ":directory",
        ":exceptions",
        ":filepath",
        ":ghc",
        ":ghc-bignum",
        ":ghc-boot",
        ":ghc-boot-th",
        ":ghc-compact",
        ":ghc-heap",
        ":ghc-prim",
        ":ghci",
        ":haskeline",
        ":hpc",
        ":integer-gmp",
        ":mtl",
        ":parsec",
        ":pretty",
        ":process",
        ":rts",
        ":semaphore-compat",
        ":stm",
        ":system-cxx-std-lib",
        ":template-haskell",
        ":terminfo",
        ":text",
        ":time",
        ":transformers",
        ":unix",
        ":xhtml",
    ],
    visibility = ["PUBLIC"],
)

haskell_prebuilt_library(
    name = "Cabal",
    version = "3.10.2.0",
    id = "Cabal-3.10.2.0-4b29",
    db = "lib/package.conf.d",
    deps = [
        ":Cabal-syntax-3.10.2.0-136f",
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":filepath-1.4.200.1-c404",
        ":mtl-2.3.1-4ed7",
        ":parsec-3.1.17.0-5705",
        ":pretty-1.1.3.6-a699",
        ":process-1.6.18.0-1a33",
        ":text-2.1.1-cd34",
        ":time-1.12.2-5921",
        ":transformers-0.6.1.0-d712",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/Cabal-3.10.2.0-4b29"],
    shared_libs = {
        "libHSCabal-3.10.2.0-4b29-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSCabal-3.10.2.0-4b29-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/Cabal-3.10.2.0-4b29/libHSCabal-3.10.2.0-4b29.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/Cabal-3.10.2.0-4b29/libHSCabal-3.10.2.0-4b29_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "Cabal-3.10.2.0-4b29", actual = ":Cabal")

haskell_prebuilt_library(
    name = "Cabal-syntax",
    version = "3.10.2.0",
    id = "Cabal-syntax-3.10.2.0-136f",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":binary-0.8.9.1-5151",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":filepath-1.4.200.1-c404",
        ":mtl-2.3.1-4ed7",
        ":parsec-3.1.17.0-5705",
        ":pretty-1.1.3.6-a699",
        ":text-2.1.1-cd34",
        ":time-1.12.2-5921",
        ":transformers-0.6.1.0-d712",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/Cabal-syntax-3.10.2.0-136f",
    ],
    shared_libs = {
        "libHSCabal-syntax-3.10.2.0-136f-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSCabal-syntax-3.10.2.0-136f-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/Cabal-syntax-3.10.2.0-136f/libHSCabal-syntax-3.10.2.0-136f.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/Cabal-syntax-3.10.2.0-136f/libHSCabal-syntax-3.10.2.0-136f_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "Cabal-syntax-3.10.2.0-136f",
    actual = ":Cabal-syntax",
)

haskell_prebuilt_library(
    name = "array",
    version = "0.5.6.0",
    id = "array-0.5.6.0-20c0",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/array-0.5.6.0-20c0"],
    shared_libs = {
        "libHSarray-0.5.6.0-20c0-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSarray-0.5.6.0-20c0-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/array-0.5.6.0-20c0/libHSarray-0.5.6.0-20c0.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/array-0.5.6.0-20c0/libHSarray-0.5.6.0-20c0_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "array-0.5.6.0-20c0", actual = ":array")

haskell_prebuilt_library(
    name = "base",
    version = "4.19.1.0",
    id = "base-4.19.1.0-cbb2",
    db = "lib/package.conf.d",
    deps = [
        ":ghc-bignum-1.3-c030",
        ":ghc-prim-0.11.0-8a73",
        ":rts-1.0.2",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/base-4.19.1.0-cbb2"],
    shared_libs = {
        "libHSbase-4.19.1.0-cbb2-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSbase-4.19.1.0-cbb2-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/base-4.19.1.0-cbb2/libHSbase-4.19.1.0-cbb2.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/base-4.19.1.0-cbb2/libHSbase-4.19.1.0-cbb2_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/base-4.19.1.0-cbb2/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "base-4.19.1.0-cbb2", actual = ":base")

haskell_prebuilt_library(
    name = "binary",
    version = "0.8.9.1",
    id = "binary-0.8.9.1-5151",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/binary-0.8.9.1-5151"],
    shared_libs = {
        "libHSbinary-0.8.9.1-5151-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSbinary-0.8.9.1-5151-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/binary-0.8.9.1-5151/libHSbinary-0.8.9.1-5151.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/binary-0.8.9.1-5151/libHSbinary-0.8.9.1-5151_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "binary-0.8.9.1-5151", actual = ":binary")

haskell_prebuilt_library(
    name = "bytestring",
    version = "0.12.1.0",
    id = "bytestring-0.12.1.0-c563",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":deepseq-1.5.0.0-d161",
        ":ghc-prim-0.11.0-8a73",
        ":template-haskell-2.21.0.0-2542",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/bytestring-0.12.1.0-c563",
    ],
    shared_libs = {
        "libHSbytestring-0.12.1.0-c563-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSbytestring-0.12.1.0-c563-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/bytestring-0.12.1.0-c563/libHSbytestring-0.12.1.0-c563.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/bytestring-0.12.1.0-c563/libHSbytestring-0.12.1.0-c563_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/bytestring-0.12.1.0-c563/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "bytestring-0.12.1.0-c563", actual = ":bytestring")

haskell_prebuilt_library(
    name = "containers",
    version = "0.6.8",
    id = "containers-0.6.8-7acc",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":deepseq-1.5.0.0-d161",
        ":template-haskell-2.21.0.0-2542",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/containers-0.6.8-7acc"],
    shared_libs = {
        "libHScontainers-0.6.8-7acc-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHScontainers-0.6.8-7acc-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/containers-0.6.8-7acc/libHScontainers-0.6.8-7acc.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/containers-0.6.8-7acc/libHScontainers-0.6.8-7acc_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "containers-0.6.8-7acc", actual = ":containers")

haskell_prebuilt_library(
    name = "deepseq",
    version = "1.5.0.0",
    id = "deepseq-1.5.0.0-d161",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":ghc-prim-0.11.0-8a73",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/deepseq-1.5.0.0-d161"],
    shared_libs = {
        "libHSdeepseq-1.5.0.0-d161-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSdeepseq-1.5.0.0-d161-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/deepseq-1.5.0.0-d161/libHSdeepseq-1.5.0.0-d161.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/deepseq-1.5.0.0-d161/libHSdeepseq-1.5.0.0-d161_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "deepseq-1.5.0.0-d161", actual = ":deepseq")

haskell_prebuilt_library(
    name = "directory",
    version = "1.3.8.1",
    id = "directory-1.3.8.1-3db4",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":filepath-1.4.200.1-c404",
        ":time-1.12.2-5921",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/directory-1.3.8.1-3db4",
    ],
    shared_libs = {
        "libHSdirectory-1.3.8.1-3db4-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSdirectory-1.3.8.1-3db4-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/directory-1.3.8.1-3db4/libHSdirectory-1.3.8.1-3db4.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/directory-1.3.8.1-3db4/libHSdirectory-1.3.8.1-3db4_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/directory-1.3.8.1-3db4/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "directory-1.3.8.1-3db4", actual = ":directory")

haskell_prebuilt_library(
    name = "exceptions",
    version = "0.10.7",
    id = "exceptions-0.10.7-6306",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":mtl-2.3.1-4ed7",
        ":stm-2.5.2.1-4277",
        ":template-haskell-2.21.0.0-2542",
        ":transformers-0.6.1.0-d712",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/exceptions-0.10.7-6306",
    ],
    shared_libs = {
        "libHSexceptions-0.10.7-6306-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSexceptions-0.10.7-6306-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/exceptions-0.10.7-6306/libHSexceptions-0.10.7-6306.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/exceptions-0.10.7-6306/libHSexceptions-0.10.7-6306_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "exceptions-0.10.7-6306", actual = ":exceptions")

haskell_prebuilt_library(
    name = "filepath",
    version = "1.4.200.1",
    id = "filepath-1.4.200.1-c404",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":deepseq-1.5.0.0-d161",
        ":exceptions-0.10.7-6306",
        ":template-haskell-2.21.0.0-2542",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/filepath-1.4.200.1-c404",
    ],
    shared_libs = {
        "libHSfilepath-1.4.200.1-c404-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSfilepath-1.4.200.1-c404-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/filepath-1.4.200.1-c404/libHSfilepath-1.4.200.1-c404.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/filepath-1.4.200.1-c404/libHSfilepath-1.4.200.1-c404_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "filepath-1.4.200.1-c404", actual = ":filepath")

haskell_prebuilt_library(
    name = "ghc",
    version = "9.8.2",
    id = "ghc-9.8.2-2c96",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":binary-0.8.9.1-5151",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":exceptions-0.10.7-6306",
        ":filepath-1.4.200.1-c404",
        ":ghc-boot-9.8.2-5e59",
        ":ghc-heap-9.8.2-dac3",
        ":ghci-9.8.2-f176",
        ":hpc-0.7.0.0-0481",
        ":process-1.6.18.0-1a33",
        ":semaphore-compat-1.0.0-cf4a",
        ":stm-2.5.2.1-4277",
        ":template-haskell-2.21.0.0-2542",
        ":time-1.12.2-5921",
        ":transformers-0.6.1.0-d712",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghc-9.8.2-2c96"],
    shared_libs = {
        "libHSghc-9.8.2-2c96-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-9.8.2-2c96-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-9.8.2-2c96/libHSghc-9.8.2-2c96.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-9.8.2-2c96/libHSghc-9.8.2-2c96_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-9.8.2-2c96", actual = ":ghc")

haskell_prebuilt_library(
    name = "ghc-bignum",
    version = "1.3",
    id = "ghc-bignum-1.3-c030",
    db = "lib/package.conf.d",
    deps = [":ghc-prim-0.11.0-8a73"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghc-bignum-1.3-c030"],
    shared_libs = {
        "libHSghc-bignum-1.3-c030-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-bignum-1.3-c030-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-bignum-1.3-c030/libHSghc-bignum-1.3-c030.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-bignum-1.3-c030/libHSghc-bignum-1.3-c030_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-bignum-1.3-c030/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-bignum-1.3-c030", actual = ":ghc-bignum")

haskell_prebuilt_library(
    name = "ghc-boot",
    version = "9.8.2",
    id = "ghc-boot-9.8.2-5e59",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":binary-0.8.9.1-5151",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":filepath-1.4.200.1-c404",
        ":ghc-boot-th-9.8.2-5f69",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghc-boot-9.8.2-5e59"],
    shared_libs = {
        "libHSghc-boot-9.8.2-5e59-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-boot-9.8.2-5e59-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-boot-9.8.2-5e59/libHSghc-boot-9.8.2-5e59.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-boot-9.8.2-5e59/libHSghc-boot-9.8.2-5e59_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-boot-9.8.2-5e59", actual = ":ghc-boot")

haskell_prebuilt_library(
    name = "ghc-boot-th",
    version = "9.8.2",
    id = "ghc-boot-th-9.8.2-5f69",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2"],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-boot-th-9.8.2-5f69",
    ],
    shared_libs = {
        "libHSghc-boot-th-9.8.2-5f69-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-boot-th-9.8.2-5f69-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-boot-th-9.8.2-5f69/libHSghc-boot-th-9.8.2-5f69.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-boot-th-9.8.2-5f69/libHSghc-boot-th-9.8.2-5f69_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-boot-th-9.8.2-5f69", actual = ":ghc-boot-th")

haskell_prebuilt_library(
    name = "ghc-compact",
    version = "0.1.0.0",
    id = "ghc-compact-0.1.0.0-a497",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":ghc-prim-0.11.0-8a73",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-compact-0.1.0.0-a497",
    ],
    shared_libs = {
        "libHSghc-compact-0.1.0.0-a497-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-compact-0.1.0.0-a497-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-compact-0.1.0.0-a497/libHSghc-compact-0.1.0.0-a497.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-compact-0.1.0.0-a497/libHSghc-compact-0.1.0.0-a497_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-compact-0.1.0.0-a497", actual = ":ghc-compact")

haskell_prebuilt_library(
    name = "ghc-heap",
    version = "9.8.2",
    id = "ghc-heap-9.8.2-dac3",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":containers-0.6.8-7acc",
        ":ghc-prim-0.11.0-8a73",
        ":rts-1.0.2",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghc-heap-9.8.2-dac3"],
    shared_libs = {
        "libHSghc-heap-9.8.2-dac3-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-heap-9.8.2-dac3-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-heap-9.8.2-dac3/libHSghc-heap-9.8.2-dac3.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-heap-9.8.2-dac3/libHSghc-heap-9.8.2-dac3_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-heap-9.8.2-dac3", actual = ":ghc-heap")

haskell_prebuilt_library(
    name = "ghc-prim",
    version = "0.11.0",
    id = "ghc-prim-0.11.0-8a73",
    db = "lib/package.conf.d",
    deps = [":rts-1.0.2"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghc-prim-0.11.0-8a73"],
    shared_libs = {
        "libHSghc-prim-0.11.0-8a73-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghc-prim-0.11.0-8a73-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-prim-0.11.0-8a73/libHSghc-prim-0.11.0-8a73.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghc-prim-0.11.0-8a73/libHSghc-prim-0.11.0-8a73_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghc-prim-0.11.0-8a73", actual = ":ghc-prim")

haskell_prebuilt_library(
    name = "ghci",
    version = "9.8.2",
    id = "ghci-9.8.2-f176",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":binary-0.8.9.1-5151",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":filepath-1.4.200.1-c404",
        ":ghc-boot-9.8.2-5e59",
        ":ghc-heap-9.8.2-dac3",
        ":ghc-prim-0.11.0-8a73",
        ":rts-1.0.2",
        ":template-haskell-2.21.0.0-2542",
        ":transformers-0.6.1.0-d712",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/ghci-9.8.2-f176"],
    shared_libs = {
        "libHSghci-9.8.2-f176-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSghci-9.8.2-f176-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghci-9.8.2-f176/libHSghci-9.8.2-f176.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/ghci-9.8.2-f176/libHSghci-9.8.2-f176_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "ghci-9.8.2-f176", actual = ":ghci")

haskell_prebuilt_library(
    name = "haskeline",
    version = "0.8.2.1",
    id = "haskeline-0.8.2.1-edf0",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":containers-0.6.8-7acc",
        ":directory-1.3.8.1-3db4",
        ":exceptions-0.10.7-6306",
        ":filepath-1.4.200.1-c404",
        ":process-1.6.18.0-1a33",
        ":stm-2.5.2.1-4277",
        ":terminfo-0.4.1.6-bee1",
        ":transformers-0.6.1.0-d712",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/haskeline-0.8.2.1-edf0",
    ],
    shared_libs = {
        "libHShaskeline-0.8.2.1-edf0-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHShaskeline-0.8.2.1-edf0-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/haskeline-0.8.2.1-edf0/libHShaskeline-0.8.2.1-edf0.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/haskeline-0.8.2.1-edf0/libHShaskeline-0.8.2.1-edf0_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "haskeline-0.8.2.1-edf0", actual = ":haskeline")

haskell_prebuilt_library(
    name = "hpc",
    version = "0.7.0.0",
    id = "hpc-0.7.0.0-0481",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":containers-0.6.8-7acc",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":filepath-1.4.200.1-c404",
        ":time-1.12.2-5921",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/hpc-0.7.0.0-0481"],
    shared_libs = {
        "libHShpc-0.7.0.0-0481-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHShpc-0.7.0.0-0481-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/hpc-0.7.0.0-0481/libHShpc-0.7.0.0-0481.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/hpc-0.7.0.0-0481/libHShpc-0.7.0.0-0481_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "hpc-0.7.0.0-0481", actual = ":hpc")

haskell_prebuilt_library(
    name = "integer-gmp",
    version = "1.1",
    id = "integer-gmp-1.1-8ef4",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":ghc-bignum-1.3-c030",
        ":ghc-prim-0.11.0-8a73",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/integer-gmp-1.1-8ef4"],
    shared_libs = {
        "libHSinteger-gmp-1.1-8ef4-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSinteger-gmp-1.1-8ef4-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/integer-gmp-1.1-8ef4/libHSinteger-gmp-1.1-8ef4.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/integer-gmp-1.1-8ef4/libHSinteger-gmp-1.1-8ef4_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "integer-gmp-1.1-8ef4", actual = ":integer-gmp")

haskell_prebuilt_library(
    name = "mtl",
    version = "2.3.1",
    id = "mtl-2.3.1-4ed7",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2", ":transformers-0.6.1.0-d712"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/mtl-2.3.1-4ed7"],
    shared_libs = {
        "libHSmtl-2.3.1-4ed7-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSmtl-2.3.1-4ed7-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/mtl-2.3.1-4ed7/libHSmtl-2.3.1-4ed7.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/mtl-2.3.1-4ed7/libHSmtl-2.3.1-4ed7_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "mtl-2.3.1-4ed7", actual = ":mtl")

haskell_prebuilt_library(
    name = "parsec",
    version = "3.1.17.0",
    id = "parsec-3.1.17.0-5705",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":mtl-2.3.1-4ed7",
        ":text-2.1.1-cd34",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/parsec-3.1.17.0-5705"],
    shared_libs = {
        "libHSparsec-3.1.17.0-5705-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSparsec-3.1.17.0-5705-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/parsec-3.1.17.0-5705/libHSparsec-3.1.17.0-5705.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/parsec-3.1.17.0-5705/libHSparsec-3.1.17.0-5705_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "parsec-3.1.17.0-5705", actual = ":parsec")

haskell_prebuilt_library(
    name = "pretty",
    version = "1.1.3.6",
    id = "pretty-1.1.3.6-a699",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":deepseq-1.5.0.0-d161",
        ":ghc-prim-0.11.0-8a73",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/pretty-1.1.3.6-a699"],
    shared_libs = {
        "libHSpretty-1.1.3.6-a699-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSpretty-1.1.3.6-a699-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/pretty-1.1.3.6-a699/libHSpretty-1.1.3.6-a699.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/pretty-1.1.3.6-a699/libHSpretty-1.1.3.6-a699_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "pretty-1.1.3.6-a699", actual = ":pretty")

haskell_prebuilt_library(
    name = "process",
    version = "1.6.18.0",
    id = "process-1.6.18.0-1a33",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":deepseq-1.5.0.0-d161",
        ":directory-1.3.8.1-3db4",
        ":filepath-1.4.200.1-c404",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/process-1.6.18.0-1a33"],
    shared_libs = {
        "libHSprocess-1.6.18.0-1a33-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSprocess-1.6.18.0-1a33-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/process-1.6.18.0-1a33/libHSprocess-1.6.18.0-1a33.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/process-1.6.18.0-1a33/libHSprocess-1.6.18.0-1a33_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/process-1.6.18.0-1a33/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "process-1.6.18.0-1a33", actual = ":process")

haskell_prebuilt_library(
    name = "rts",
    version = "1.0.2",
    id = "rts-1.0.2",
    db = "lib/package.conf.d",
    deps = [],
    import_dirs = [],
    shared_libs = {
        "libHSrts-1.0.2-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSrts-1.0.2-ghc9.8.2.so",
        "libffi.so": "lib/x86_64-linux-ghc-9.8.2/libffi.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/rts-1.0.2/libHSrts-1.0.2.a",
        "lib/x86_64-linux-ghc-9.8.2/rts-1.0.2/libCffi.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/rts-1.0.2/libHSrts-1.0.2_p.a",
        "lib/x86_64-linux-ghc-9.8.2/rts-1.0.2/libCffi_p.a",
    ],
    cxx_header_dirs = ["lib/x86_64-linux-ghc-9.8.2/rts-1.0.2/include"],
    exported_linker_flags = [
        "-Wl,-u,base_GHCziTopHandler_runIO_closure",
        "-Wl,-u,base_GHCziTopHandler_runNonIO_closure",
        "-Wl,-u,ghczmprim_GHCziTupleziPrim_Z0T_closure",
        "-Wl,-u,ghczmprim_GHCziTypes_True_closure",
        "-Wl,-u,ghczmprim_GHCziTypes_False_closure",
        "-Wl,-u,base_GHCziPack_unpackCString_closure",
        "-Wl,-u,base_GHCziWeakziFinalizze_runFinalizzerBatch_closure",
        "-Wl,-u,base_GHCziIOziException_stackOverflow_closure",
        "-Wl,-u,base_GHCziIOziException_heapOverflow_closure",
        "-Wl,-u,base_GHCziIOziException_allocationLimitExceeded_closure",
        "-Wl,-u,base_GHCziIOziException_blockedIndefinitelyOnMVar_closure",
        "-Wl,-u,base_GHCziIOziException_blockedIndefinitelyOnSTM_closure",
        "-Wl,-u,base_GHCziIOziException_cannotCompactFunction_closure",
        "-Wl,-u,base_GHCziIOziException_cannotCompactPinned_closure",
        "-Wl,-u,base_GHCziIOziException_cannotCompactMutable_closure",
        "-Wl,-u,base_GHCziIOPort_doubleReadException_closure",
        "-Wl,-u,base_ControlziExceptionziBase_nonTermination_closure",
        "-Wl,-u,base_ControlziExceptionziBase_nestedAtomically_closure",
        "-Wl,-u,base_GHCziEventziThread_blockedOnBadFD_closure",
        "-Wl,-u,base_GHCziConcziSync_runSparks_closure",
        "-Wl,-u,base_GHCziConcziIO_ensureIOManagerIsRunning_closure",
        "-Wl,-u,base_GHCziConcziIO_interruptIOManager_closure",
        "-Wl,-u,base_GHCziConcziIO_ioManagerCapabilitiesChanged_closure",
        "-Wl,-u,base_GHCziConcziSignal_runHandlersPtr_closure",
        "-Wl,-u,base_GHCziTopHandler_flushStdHandles_closure",
        "-Wl,-u,base_GHCziTopHandler_runMainIO_closure",
        "-Wl,-u,ghczmprim_GHCziTypes_Czh_con_info",
        "-Wl,-u,ghczmprim_GHCziTypes_Izh_con_info",
        "-Wl,-u,ghczmprim_GHCziTypes_Fzh_con_info",
        "-Wl,-u,ghczmprim_GHCziTypes_Dzh_con_info",
        "-Wl,-u,ghczmprim_GHCziTypes_Wzh_con_info",
        "-Wl,-u,base_GHCziPtr_Ptr_con_info",
        "-Wl,-u,base_GHCziPtr_FunPtr_con_info",
        "-Wl,-u,base_GHCziInt_I8zh_con_info",
        "-Wl,-u,base_GHCziInt_I16zh_con_info",
        "-Wl,-u,base_GHCziInt_I32zh_con_info",
        "-Wl,-u,base_GHCziInt_I64zh_con_info",
        "-Wl,-u,base_GHCziWord_W8zh_con_info",
        "-Wl,-u,base_GHCziWord_W16zh_con_info",
        "-Wl,-u,base_GHCziWord_W32zh_con_info",
        "-Wl,-u,base_GHCziWord_W64zh_con_info",
        "-Wl,-u,base_GHCziStable_StablePtr_con_info",
        "-Wl,-u,hs_atomic_add8",
        "-Wl,-u,hs_atomic_add16",
        "-Wl,-u,hs_atomic_add32",
        "-Wl,-u,hs_atomic_add64",
        "-Wl,-u,hs_atomic_sub8",
        "-Wl,-u,hs_atomic_sub16",
        "-Wl,-u,hs_atomic_sub32",
        "-Wl,-u,hs_atomic_sub64",
        "-Wl,-u,hs_atomic_and8",
        "-Wl,-u,hs_atomic_and16",
        "-Wl,-u,hs_atomic_and32",
        "-Wl,-u,hs_atomic_and64",
        "-Wl,-u,hs_atomic_nand8",
        "-Wl,-u,hs_atomic_nand16",
        "-Wl,-u,hs_atomic_nand32",
        "-Wl,-u,hs_atomic_nand64",
        "-Wl,-u,hs_atomic_or8",
        "-Wl,-u,hs_atomic_or16",
        "-Wl,-u,hs_atomic_or32",
        "-Wl,-u,hs_atomic_or64",
        "-Wl,-u,hs_atomic_xor8",
        "-Wl,-u,hs_atomic_xor16",
        "-Wl,-u,hs_atomic_xor32",
        "-Wl,-u,hs_atomic_xor64",
        "-Wl,-u,hs_cmpxchg8",
        "-Wl,-u,hs_cmpxchg16",
        "-Wl,-u,hs_cmpxchg32",
        "-Wl,-u,hs_cmpxchg64",
        "-Wl,-u,hs_xchg8",
        "-Wl,-u,hs_xchg16",
        "-Wl,-u,hs_xchg32",
        "-Wl,-u,hs_xchg64",
        "-Wl,-u,hs_atomicread8",
        "-Wl,-u,hs_atomicread16",
        "-Wl,-u,hs_atomicread32",
        "-Wl,-u,hs_atomicread64",
        "-Wl,-u,hs_atomicwrite8",
        "-Wl,-u,hs_atomicwrite16",
        "-Wl,-u,hs_atomicwrite32",
        "-Wl,-u,hs_atomicwrite64",
        "-Wl,-u,base_GHCziStackziCloneStack_StackSnapshot_closure",
    ],
    visibility = ["PUBLIC"],
)

alias(name = "rts-1.0.2", actual = ":rts")

haskell_prebuilt_library(
    name = "semaphore-compat",
    version = "1.0.0",
    id = "semaphore-compat-1.0.0-cf4a",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":exceptions-0.10.7-6306",
        ":unix-2.8.4.0-d7dc",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/semaphore-compat-1.0.0-cf4a",
    ],
    shared_libs = {
        "libHSsemaphore-compat-1.0.0-cf4a-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSsemaphore-compat-1.0.0-cf4a-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/semaphore-compat-1.0.0-cf4a/libHSsemaphore-compat-1.0.0-cf4a.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/semaphore-compat-1.0.0-cf4a/libHSsemaphore-compat-1.0.0-cf4a_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "semaphore-compat-1.0.0-cf4a",
    actual = ":semaphore-compat",
)

haskell_prebuilt_library(
    name = "stm",
    version = "2.5.2.1",
    id = "stm-2.5.2.1-4277",
    db = "lib/package.conf.d",
    deps = [":array-0.5.6.0-20c0", ":base-4.19.1.0-cbb2"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/stm-2.5.2.1-4277"],
    shared_libs = {
        "libHSstm-2.5.2.1-4277-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSstm-2.5.2.1-4277-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/stm-2.5.2.1-4277/libHSstm-2.5.2.1-4277.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/stm-2.5.2.1-4277/libHSstm-2.5.2.1-4277_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "stm-2.5.2.1-4277", actual = ":stm")

haskell_prebuilt_library(
    name = "system-cxx-std-lib",
    version = "1.0",
    id = "system-cxx-std-lib-1.0",
    db = "lib/package.conf.d",
    deps = [],
    import_dirs = [],
    shared_libs = {},
    static_libs = [],
    profiled_static_libs = [],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "system-cxx-std-lib-1.0",
    actual = ":system-cxx-std-lib",
)

haskell_prebuilt_library(
    name = "template-haskell",
    version = "2.21.0.0",
    id = "template-haskell-2.21.0.0-2542",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":ghc-boot-th-9.8.2-5f69",
        ":ghc-prim-0.11.0-8a73",
        ":pretty-1.1.3.6-a699",
    ],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/template-haskell-2.21.0.0-2542",
    ],
    shared_libs = {
        "libHStemplate-haskell-2.21.0.0-2542-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHStemplate-haskell-2.21.0.0-2542-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/template-haskell-2.21.0.0-2542/libHStemplate-haskell-2.21.0.0-2542.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/template-haskell-2.21.0.0-2542/libHStemplate-haskell-2.21.0.0-2542_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "template-haskell-2.21.0.0-2542",
    actual = ":template-haskell",
)

haskell_prebuilt_library(
    name = "terminfo",
    version = "0.4.1.6",
    id = "terminfo-0.4.1.6-bee1",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/terminfo-0.4.1.6-bee1"],
    shared_libs = {
        "libHSterminfo-0.4.1.6-bee1-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSterminfo-0.4.1.6-bee1-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/terminfo-0.4.1.6-bee1/libHSterminfo-0.4.1.6-bee1.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/terminfo-0.4.1.6-bee1/libHSterminfo-0.4.1.6-bee1_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "terminfo-0.4.1.6-bee1", actual = ":terminfo")

haskell_prebuilt_library(
    name = "text",
    version = "2.1.1",
    id = "text-2.1.1-cd34",
    db = "lib/package.conf.d",
    deps = [
        ":array-0.5.6.0-20c0",
        ":base-4.19.1.0-cbb2",
        ":binary-0.8.9.1-5151",
        ":bytestring-0.12.1.0-c563",
        ":deepseq-1.5.0.0-d161",
        ":ghc-prim-0.11.0-8a73",
        ":template-haskell-2.21.0.0-2542",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/text-2.1.1-cd34"],
    shared_libs = {
        "libHStext-2.1.1-cd34-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHStext-2.1.1-cd34-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/text-2.1.1-cd34/libHStext-2.1.1-cd34.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/text-2.1.1-cd34/libHStext-2.1.1-cd34_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "text-2.1.1-cd34", actual = ":text")

haskell_prebuilt_library(
    name = "time",
    version = "1.12.2",
    id = "time-1.12.2-5921",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2", ":deepseq-1.5.0.0-d161"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/time-1.12.2-5921"],
    shared_libs = {
        "libHStime-1.12.2-5921-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHStime-1.12.2-5921-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/time-1.12.2-5921/libHStime-1.12.2-5921.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/time-1.12.2-5921/libHStime-1.12.2-5921_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/time-1.12.2-5921/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "time-1.12.2-5921", actual = ":time")

haskell_prebuilt_library(
    name = "transformers",
    version = "0.6.1.0",
    id = "transformers-0.6.1.0-d712",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2"],
    import_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/transformers-0.6.1.0-d712",
    ],
    shared_libs = {
        "libHStransformers-0.6.1.0-d712-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHStransformers-0.6.1.0-d712-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/transformers-0.6.1.0-d712/libHStransformers-0.6.1.0-d712.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/transformers-0.6.1.0-d712/libHStransformers-0.6.1.0-d712_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(
    name = "transformers-0.6.1.0-d712",
    actual = ":transformers",
)

haskell_prebuilt_library(
    name = "unix",
    version = "2.8.4.0",
    id = "unix-2.8.4.0-d7dc",
    db = "lib/package.conf.d",
    deps = [
        ":base-4.19.1.0-cbb2",
        ":bytestring-0.12.1.0-c563",
        ":filepath-1.4.200.1-c404",
        ":time-1.12.2-5921",
    ],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/unix-2.8.4.0-d7dc"],
    shared_libs = {
        "libHSunix-2.8.4.0-d7dc-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSunix-2.8.4.0-d7dc-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/unix-2.8.4.0-d7dc/libHSunix-2.8.4.0-d7dc.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/unix-2.8.4.0-d7dc/libHSunix-2.8.4.0-d7dc_p.a",
    ],
    cxx_header_dirs = [
        "lib/x86_64-linux-ghc-9.8.2/unix-2.8.4.0-d7dc/include",
    ],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "unix-2.8.4.0-d7dc", actual = ":unix")

haskell_prebuilt_library(
    name = "xhtml",
    version = "3000.2.2.1",
    id = "xhtml-3000.2.2.1-38ba",
    db = "lib/package.conf.d",
    deps = [":base-4.19.1.0-cbb2"],
    import_dirs = ["lib/x86_64-linux-ghc-9.8.2/xhtml-3000.2.2.1-38ba"],
    shared_libs = {
        "libHSxhtml-3000.2.2.1-38ba-ghc9.8.2.so": "lib/x86_64-linux-ghc-9.8.2/libHSxhtml-3000.2.2.1-38ba-ghc9.8.2.so",
    },
    static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/xhtml-3000.2.2.1-38ba/libHSxhtml-3000.2.2.1-38ba.a",
    ],
    profiled_static_libs = [
        "lib/x86_64-linux-ghc-9.8.2/xhtml-3000.2.2.1-38ba/libHSxhtml-3000.2.2.1-38ba_p.a",
    ],
    cxx_header_dirs = [],
    exported_linker_flags = [],
    visibility = ["PUBLIC"],
)

alias(name = "xhtml-3000.2.2.1-38ba", actual = ":xhtml")
