# buildifier: disable=module-docstring
load("//rules/haskell:defs.bzl", "haskell_binary")

haskell_binary(
    name = "setup_simple",
    srcs = {"Main.hs": "setup_simple.hs"},
    toolchain_libs = ["base", "bytestring", "containers", "filepath", "Cabal", "Cabal-syntax"],
    visibility = ["PUBLIC"],
)

haskell_binary(
    name = "setup_configure",
    srcs = {"Main.hs": "setup_configure.hs"},
    toolchain_libs = ["base", "Cabal"],
    visibility = ["PUBLIC"],
)
