#!/bin/sh
# Locate the source file of each module of a component, the way Cabal does.
#
#   find_modules.sh SRCDIR OUT [--dir=DIR]... [--module=MODULE]... [--main=FILE]
#
# A module is looked up in every DIR, first as the input of a preprocessor and
# then as a Haskell source file (see Distribution.Simple.PreProcess). The
# result is a JSON object:
#
#   { "modules": { "Data.Foo": { "dir": "src", "file": "Data/Foo.x", "ext": "x" } }
#   , "main": { "dir": "app", "file": "Main.hs", "ext": "hs" }
#   }
#
# Modules that are not found are left out; deciding whether that is an error
# is up to the caller, since they could be autogenerated.
set -eu

srcdir=$1
out=$2
shift 2

pp_exts="chs hsc x y ly cpphs"
hs_exts="hs lhs hsig lhsig"

nl='
'
dirs=
modules=
main=
for arg in "$@"; do
    case "$arg" in
    --dir=*) dirs="$dirs${arg#--dir=}$nl" ;;
    --module=*) modules="$modules${arg#--module=}$nl" ;;
    --main=*) main=${arg#--main=} ;;
    *)
        echo "find_modules.sh: unexpected argument: $arg" >&2
        exit 2
        ;;
    esac
done

# lookup BASE EXTS: sets found_dir, found_file and found_ext
lookup() {
    while IFS= read -r dir; do
        [ -n "$dir" ] || continue
        for e in $2; do
            if [ -f "$srcdir/$dir/$1.$e" ]; then
                found_dir=$dir
                found_file=$1.$e
                found_ext=$e
                return 0
            fi
        done
    done <<EOT
$dirs
EOT
    return 1
}

quote() {
    printf '"%s"' "$(printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
}

entry() {
    printf '{"dir": %s, "file": %s, "ext": %s}' "$(quote "$found_dir")" "$(quote "$found_file")" "$(quote "$found_ext")"
}

{
    printf '{"modules": {'
    sep=
    while IFS= read -r module; do
        [ -n "$module" ] || continue
        base=$(printf '%s' "$module" | tr . /)
        if lookup "$base" "$pp_exts" || lookup "$base" "$hs_exts"; then
            printf '%s\n  %s: %s' "$sep" "$(quote "$module")" "$(entry)"
            sep=,
        fi
    done <<EOT
$modules
EOT
    printf '\n}'

    if [ -n "$main" ]; then
        base=${main%.*}
        ext=${main##*.}
        if lookup "$base" "$pp_exts" || lookup "$base" "$ext"; then
            printf ',\n"main": %s' "$(entry)"
        fi
    fi
    printf '\n}\n'
} >"$out"
