export_file(
    name = "setup_simple.hs",
    visibility = ["PUBLIC"],
)

export_file(
    name = "setup_configure.hs",
    visibility = ["PUBLIC"],
)

export_file(
    name = "setup_make.hs",
    visibility = ["PUBLIC"],
)
