"""
Macros to import a plan generated by cabal-install into buck2.
"""

load("//rules/haskell:defs.bzl", "haskell_binary")
load("build.bzl", "build")
load("build_legacy.bzl", "build_legacy")
load("pkg_src.bzl", "pkg_src")
load("pre_existing_unit.bzl", "pre_existing_unit")

_as_source = lambda dep: ":{}".format(dep)

def interpret_plan(name: str, planjson: str):
    """Interprets a cabal-install generated plan.json file into build rules.

    Args:
        name: The name of the rule.
        planjson: The JSON-encoded cabal install plan.
    """

    plan = json.decode(planjson)
    units = map(_normalise_legacy_unit, plan["install-plan"])

    # NOTE: every unit uses the toolchain (toolchains//:haskell), which
    # has to be the compiler the plan was made with (plan["compiler-id"]).

    # Pre-existing units come from the compiler's global package db and are
    # referred to by package name when compiling a Setup.hs.
    pre_existing = {
        unit["id"]: unit["pkg-name"]
        for unit in units
        if unit["type"] == "pre-existing"
    }

    srcs = {}

    for unit in units:
        if unit["type"] == "configured" and unit["style"] == "global":
            pkg_id = "{pkg-name}-{pkg-version}".format(**unit)

            if pkg_id not in srcs:
                srcs[pkg_id] = pkg_id
                pkg_src(
                    name = pkg_id,
                    pkg_name = unit["pkg-name"],
                    pkg_version = unit["pkg-version"],
                    pkg_src = unit["pkg-src"],
                    pkg_src_sha256 = unit["pkg-src-sha256"],
                    pkg_cabal_sha256 = unit.get("pkg-cabal-sha256"),
                    pkg_cabal_revision = unit.get("pkg-cabal-revision"),
                    pkg_cabal_size = unit.get("pkg-cabal-size"),
                )

            is_legacy_build = "components" in unit

            if is_legacy_build:
                setup_depends = unit["setup-depends"]
                haskell_binary(
                    name = "{}-setup".format(pkg_id),
                    toolchain_libs = [pre_existing[d] for d in setup_depends if d in pre_existing] if setup_depends else ["base", "Cabal"],
                    deps = [_as_source(d) for d in setup_depends if d not in pre_existing],
                    srcs = {"Main.hs": ":{}[Setup.hs]".format(pkg_id)},
                    visibility = ["PUBLIC"],
                )

                build_legacy(
                    name = unit["id"],
                    unit_id = unit["id"],
                    pkg_name = unit["pkg-name"],
                    pkg_version = unit["pkg-version"],
                    flags = unit["flags"],
                    deps = map(_as_source, unit.get("depends", [])),
                    exec_deps = map(_as_source, unit.get("exe-depends", [])),
                    setup = _as_source("{}-setup".format(pkg_id)),
                    src = _as_source(pkg_id),
                )
            else:
                build(
                    name = unit["id"],
                    unit_id = unit["id"],
                    pkg_name = unit["pkg-name"],
                    pkg_version = unit["pkg-version"],
                    component_name = unit.get("component-name"),
                    src = _as_source(pkg_id),
                    flags = unit["flags"],
                    deps = map(_as_source, unit.get("depends", [])),
                    exec_deps = map(_as_source, unit.get("exe-depends", [])),
                )

        elif unit["type"] == "pre-existing":
            pre_existing_unit(
                name = unit["id"],
                unit_id = unit["id"],
                pkg_name = unit["pkg-name"],
                pkg_version = unit["pkg-version"],
                deps = map(_as_source, unit["depends"]),
            )

def _normalise_legacy_unit(unit):
    if "components" in unit:
        components = unit["components"]

        depends = []
        exe_depends = []
        for n, c in components.items():
            if n != "setup":
                depends += c["depends"]
                exe_depends += c["exe-depends"]

        setup_depends = components["setup"]["depends"] if "setup" in components else []

        unit.update({
            "depends": depends,
            "exe-depends": exe_depends,
            "setup-depends": setup_depends,
        })

    return unit
